repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-json
      - id: check-yaml
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        args: ["--filter-files"]
  - repo: https://github.com/psf/black
    rev: 21.4b1
    hooks:
      - id: black
        args: [--safe]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
      - id: flake8
        args: ["--config=.flake8"]
        additional_dependencies: ["flake8-bugbear==21.4.3"]
